styler::style_pkg(filetype = c(".R", ".Rmd", ".Rmarkdown", ".Rnw"), indent_by = 4L, start_comments_with_one_space = TRUE)
styler::style_dir("../", filetype = c(".R", ".Rmd", ".Rmarkdown", ".Rnw"), indent_by = 4L, start_comments_with_one_space = TRUE, recursive = FALSE)
source(here::here('reference_data','build_package_data.R'))
devtools::document()
devtools::test()
